# Generated by Django 4.1 on 2023-09-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='phone',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='petresult',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='petresultper',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='photo',
            field=models.TextField(),
        ),
    ]
