# Generated by Django 4.1 on 2023-09-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_auth_phone_alter_auth_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='petresultper',
            field=models.TextField(blank=True, null=True),
        ),
    ]
