# Generated by Django 4.1 on 2023-09-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_diagnosis_petresultper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='petresultper',
        ),
    ]
